import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import HomeLayout from "./HomeLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en">
      <HomeLayout>
        {children}
      </HomeLayout>
    </html>
  );
}
